2fa_login:
    path: /2fa
    defaults:
        _controller: "scheb_two_factor.form_controller::form"

2fa_login_check:
    path: /2fa_check

2fa_browser_check:
    path: /2fa_browser_check

2fa_ip_check:
    path: /2fa_ip_check